"""Ackermann-first path generation utilities."""

from .boustrophedon import BoustrophedonError, generate_lawnmower
from .ros_path import PathRow, poses_to_rows, read_path_csv, write_path_csv
from .calibration import (
    TimedPose2D,
    TrajectoryError,
    TurnRadiusEstimate,
    align_by_time,
    compute_trajectory_error,
    endpoint_error,
    estimate_turn_radius,
    fit_arc_radius_by_distance_and_heading,
    fit_circle_radius,
    interpolate_pose,
    load_timed_xytheta_csv,
    load_xytheta_csv,
    trajectory_distance,
)
from .primitives import (
    CurvatureViolation,
    InvalidPrimitive,
    Pose2D,
    assert_curvature_within,
    curvatures,
    max_curvature,
    normalize_angle,
    path_length,
    sample_arc,
    sample_line,
    sample_u_turn,
)

__all__ = [
    "BoustrophedonError",
    "CurvatureViolation",
    "InvalidPrimitive",
    "PathRow",
    "Pose2D",
    "TimedPose2D",
    "TrajectoryError",
    "TurnRadiusEstimate",
    "align_by_time",
    "assert_curvature_within",
    "compute_trajectory_error",
    "curvatures",
    "endpoint_error",
    "estimate_turn_radius",
    "fit_arc_radius_by_distance_and_heading",
    "fit_circle_radius",
    "generate_lawnmower",
    "interpolate_pose",
    "load_timed_xytheta_csv",
    "load_xytheta_csv",
    "max_curvature",
    "normalize_angle",
    "path_length",
    "poses_to_rows",
    "read_path_csv",
    "sample_arc",
    "sample_line",
    "sample_u_turn",
    "trajectory_distance",
    "write_path_csv",
]
